import PDFDocument from 'pdfkit';
import type { Response } from 'express';
import type { GeneratedPaper } from '../types/index';

const DIFF_COLORS: Record<string, string> = {
  Easy: '#166534',
  Medium: '#854D0E',
  Hard: '#991B1B',
};

export function generatePDF(paper: GeneratedPaper, res: Response): void {
  const doc = new PDFDocument({
    margin: 50,
    size: 'A4',
    info: {
      Title: paper.title,
      Author: 'VedaAI',
      Subject: paper.subject,
    },
  });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${paper.title.replace(/[^a-z0-9]/gi, '_')}.pdf"`);
  doc.pipe(res);

  // ── Header ──
  doc.rect(50, 40, doc.page.width - 100, 80).fill('#1A1A1A');
  doc
    .fillColor('#FFFFFF')
    .fontSize(16)
    .font('Helvetica-Bold')
    .text(paper.school, 50, 55, { align: 'center', width: doc.page.width - 100 });
  doc
    .fontSize(12)
    .font('Helvetica')
    .text(`Subject: ${paper.subject}  |  Class: ${paper.className}`, 50, 78, {
      align: 'center',
      width: doc.page.width - 100,
    });
  doc
    .fontSize(11)
    .text(paper.title, 50, 96, { align: 'center', width: doc.page.width - 100 });

  // ── Meta row ──
  doc.fillColor('#1A1A1A').moveDown(0.5);
  const metaY = 135;
  doc.fontSize(10).font('Helvetica').fillColor('#444444');
  doc.text(`Time Allowed: ${paper.timeAllowed}`, 50, metaY);
  doc.text(`Maximum Marks: ${paper.maxMarks}`, 0, metaY, { align: 'right' });

  doc.moveTo(50, 155).lineTo(doc.page.width - 50, 155).strokeColor('#CCCCCC').lineWidth(0.5).stroke();

  // ── General Instructions ──
  if (paper.generalInstructions?.length) {
    doc.moveDown(0.5).fontSize(10).font('Helvetica-Bold').fillColor('#1A1A1A').text('General Instructions:', 50);
    paper.generalInstructions.forEach((inst, i) => {
      doc.fontSize(9).font('Helvetica').fillColor('#555555').text(`${i + 1}. ${inst}`, 60);
    });
  }

  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#CCCCCC').lineWidth(0.5).stroke();

  // ── Student Info ──
  doc.moveDown(0.5);
  const infoY = doc.y;
  doc.fontSize(10).font('Helvetica').fillColor('#555555');
  doc.text('Name: _______________________________', 50, infoY);
  doc.text('Roll No: ________________', 260, infoY);
  doc.text('Section: ________', 430, infoY);

  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#CCCCCC').lineWidth(0.5).stroke();
  doc.moveDown(0.5);

  // ── Sections ──
  for (const section of paper.sections) {
    // Section header
    doc.rect(50, doc.y, doc.page.width - 100, 20).fill('#F5F4F0');
    doc
      .fillColor('#1A1A1A')
      .fontSize(11)
      .font('Helvetica-Bold')
      .text(`${section.title} — ${section.questionType}`, 58, doc.y - 15);
    doc.moveDown(0.3);

    if (section.instruction) {
      doc.fontSize(9).font('Helvetica-Oblique').fillColor('#666666').text(section.instruction, 58);
      doc.moveDown(0.4);
    }

    // Questions
    for (const q of section.questions) {
      if (doc.y > doc.page.height - 120) {
        doc.addPage();
      }

      const qY = doc.y;
      // Question number circle
      doc.circle(62, qY + 6, 8).fill('#E8510A');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold').text(String(q.id), 58, qY + 2, { width: 8, align: 'center' });

      // Question text
      doc.fillColor('#1A1A1A').fontSize(10).font('Helvetica').text(q.text, 78, qY, { width: doc.page.width - 130 });

      doc.moveDown(0.2);

      // Difficulty + marks tags
      const tagY = doc.y;
      const diffColor = DIFF_COLORS[q.difficulty] || '#444444';
      doc.fillColor(diffColor).fontSize(8).font('Helvetica-Bold').text(`[${q.difficulty}]`, 78, tagY);
      doc
        .fillColor('#666666')
        .fontSize(8)
        .font('Helvetica')
        .text(`${q.marks} mark${q.marks > 1 ? 's' : ''}`, 125, tagY);

      doc.moveDown(0.6);
    }

    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#EEEEEE').lineWidth(0.3).stroke();
    doc.moveDown(0.5);
  }

  // ── Footer ──
  doc.moveDown(1);
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#AAAAAA')
    .text('— End of Question Paper —', { align: 'center' });
  doc.text('Generated by VedaAI · Delhi Public School', { align: 'center' });

  doc.end();
}
